name: Release staging build

on:
  push:
    branches: [ "release_staging" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        
      - run: fastlane run set_info_plist_value path:Info.plist key:MyReplacableKey value:KEYED_TO_STAGING  
      
      - name: Find and Replace
        run: sed -i '' 's/ConfigManager.API_STAGING_URI/ConfigManager.TOTAL_CUSTOM_URI/g' ReplaceInMe
        
      - run: cp ./release_staging/GoogleFile ./GoogleFile
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Creating Staging Release
